apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  network: mainnet
  provider: internal

bases:
  - ../../envs/test-phase1
  - ../../scripts

resources:
  - ../../bases/data-transport-layer
  - ../../bases/l2geth
  - ../../bases/l1chain
  - ../../bases/deployer
  - ../../bases/batch-submitter
  - ../../bases/relayer
  - ./pv.yaml
  - ./pvc.yaml
  - ./sc.yaml
